s1 = input("Enter the first string:")
s2 = input("Enter the second string:")
print("Added together: "+s1+s2)
print("s1 repeated 3 times: "+s1*3)
print("s2 repeated 3 times: "+s2*3)
print("Uppercase and added together: "+s1.upper()+s2.upper())
print("s1 Lowercase and 5 times: "+s1.lower()*5)
print("s2 Lowercase and 5 times: "+s2.lower()*5)
print("s1 3rd letter: "+s1[2])
print("s2 3rd letter: "+s2[2])
print("s1 strings sliced 3-9: "+s1[3:9])
print("s2 strings sliced 3-9: "+s2[3:9])
